FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "raylib-beef"
TargetType = "BeefLib"
StartupObject = "beef.Program"
DefaultNamespace = "Raylib"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\dist\\x64\\raylib.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/*.dll\")"]

[Configs.Release.Win64]
CLibType = "Dynamic"
LibPaths = ["$(ProjectDir)\\dist\\x64\\raylib.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/*.dll\")"]

[Configs.Paranoid.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/*.dll\")"]

[Configs.Test.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/*.dll\")"]
